### ISSUE TITLE
Unable to run depth estimation

### ISSUE THREAD

**Issue by FitashUlHaq** [erdos-project/pylot#186]
I am trying to execute the depth estimation config file and getting this error

Traceback (most recent call last):
  File "pylot.py", line 259, in main
    node_handle, control_display_stream = driver()
  File "pylot.py", line 154, in driver
    depth_camera_stream)
  File "/home/erdos/workspace/pylot/pylot/component_creator.py", line 249, in add_depth
    transform, vehicle_id_stream)
TypeError: add_left_right_cameras() missing 1 required positional argument: 'release_sensor_stream'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pylot.py", line 272, in <module>
    app.run(main)
  File "/home/erdos/.local/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/erdos/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "pylot.py", line 267, in main
    shutdown_pylot(node_handle, client, world)
UnboundLocalError: local variable 'node_handle' referenced before assignment

**Comment by ICGog** [comment]
Closing this issue as I've fixed the connections between the operators in this commit: https://github.com/erdos-project/pylot/commit/ec62f71e261932995a975d8341c37f6a55cfda3a . However, the depth estimation operator is still not complete (see #67).
