### ISSUE TITLE
Running pylot with a single docker exec command

### ISSUE THREAD

**Issue by SepShr** [erdos-project/pylot#275]
Hello all,

I have been trying to parallelize automated docker-based simulations. To do so, I have automated the steps to update the configuration and run the carla and pylot processes inside the container. However, the current steps include running commands using the Python `subprocess` module (e.g., `subprocess.run()` and `subprocess.popen()`). This is problematic since apparently such processes are not pickleable and the `processpoolexecutor` raises an exception. Therefore, it is necessary to be able to manage the container and run pylot in it using the `docker-py` library. All of this explanation is a long way of saying I need to be able to run pylot using a single `docker exec` command rather than having to go inside it using `bash` or SSH into it, as mentioned in the [quick start guide](https://pylot.readthedocs.io/en/latest/quick_start.html).

Different variations of the exec command that I have tried to run and their output are as follows:
```bash

~$ nvidia-docker exec -it pylot python3 pylot.py --flagfile=configs/mlcshe_config.conf
Traceback (most recent call last):
  File "pylot.py", line 13, in <module>
    from pylot.simulation.utils import get_world, set_asynchronous_mode
  File "/home/erdos/workspace/pylot/pylot/simulation/utils.py", line 15, in <module>
    from pylot.simulation.carla_handler import carla_handle
  File "/home/erdos/workspace/pylot/pylot/simulation/carla_handler.py", line 1, in <module>
    from carla import  Transform,Location, Rotation, VehicleLightState
ModuleNotFoundError: No module named 'carla'


~$ nvidia-docker exec -it pylot /usr/bin/python3 pylot.py --flagfile=configs/mlcshe/mlcshe_config.conf
Traceback (most recent call last):
  File "pylot.py", line 13, in <module>
    from pylot.simulation.utils import get_world, set_asynchronous_mode
  File "/home/erdos/workspace/pylot/pylot/simulation/utils.py", line 15, in <module>
    from pylot.simulation.carla_handler import carla_handle
  File "/home/erdos/workspace/pylot/pylot/simulation/carla_handler.py", line 1, in <module>
    from carla import  Transform,Location, Rotation, VehicleLightState
ModuleNotFoundError: No module named 'carla'


~$ nvidia-docker exec -it -e PYTHONPATH=/home/erdos/workspace/pylot/dependencies/CARLA_0.9.10.1 pylot  /usr/bin/python3 pylot.py --flagfile=configs/mlcshe/mlcshe_config.conf
Traceback (most recent call last):
  File "pylot.py", line 13, in <module>
    from pylot.simulation.utils import get_world, set_asynchronous_mode
  File "/home/erdos/workspace/pylot/pylot/simulation/utils.py", line 15, in <module>
    from pylot.simulation.carla_handler import carla_handle
  File "/home/erdos/workspace/pylot/pylot/simulation/carla_handler.py", line 1, in <module>
    from carla import  Transform,Location, Rotation, VehicleLightState
ModuleNotFoundError: No module named 'carla'


~$ nvidia-docker exec -it -e PYTHONPATH=/home/erdos/workspace/pylot/dependencies/CARLA_0.9.10.1 pylot /bin/bash -c '/usr/bin/python3 pylot.py --flagfile=configs/mlcshe/mlcshe_config.conf'
Traceback (most recent call last):
  File "pylot.py", line 13, in <module>
    from pylot.simulation.utils import get_world, set_asynchronous_mode
  File "/home/erdos/workspace/pylot/pylot/simulation/utils.py", line 15, in <module>
    from pylot.simulation.carla_handler import carla_handle
  File "/home/erdos/workspace/pylot/pylot/simulation/carla_handler.py", line 1, in <module>
    from carla import  Transform,Location, Rotation, VehicleLightState
ModuleNotFoundError: No module named 'carla'

```

Kindly note that the configuration file, i.e., `configs/mlcshe/mlcshe_config.conf`, is a custom configuration that I use for my simulations. To replicate the issue, you can use other available configurations such as `detection.conf`.

Many thanks for your help in advance.

**Comment by SepShr** [comment]
## Update
Adding the environment variables to the `docker exec` command seems to do the trick!

```bash
    nvidia-docker exec -i -t -e PYTHONPATH=/home/erdos/workspace/pylot/dependencies/:/home/erdos/workspace/pylot/dependencies/lanenet:/home/erdos/workspace/pylot/dependencies/CARLA_0.9.10.1/PythonAPI/carla/dist/carla-0.9.10-py3.7-linux-x86_64.egg:/home/erdos/workspace/pylot/dependencies/CARLA_0.9.10.1/PythonAPI/carla/:/home/erdos/workspace/pylot/dependencies/CARLA_0.9.10.1/PythonAPI/carla/agents/:/home/erdos/workspace/pylot/dependencies/CARLA_0.9.10.1/PythonAPI/:/home/erdos/workspace/scenario_runner pylot python3 pylot.py --flagfile=configs/mlcshe/mlcshe_config.conf 
```
